<?php if (count($articles)) { ?>
  <?php
  foreach($articles as $article) {
    $url = '/' . $article->getTimestamp('Y') . '/' . $article->getTimestamp('m') . '/' . $article->getSlug();
    ?>
    <article>
      <h1><a href="<?php echo $url ?>"><?php echo $article->getTitle(); ?></a></h1>
      <?php echo $article->getParsedIntro(); ?>
      <footer>
        <ul>
          <li><?php echo $article->getTimestamp('d-m-Y'); ?></li>
          <li><?php echo $article->getTimestamp('H:i'); ?></li>
          <li>Tags: <?php echo implode(', ', $article->getTags()); ?></li>
          <li>Comments <?php echo $article->getCommentCount(); ?></li>
        </ul>
      </footer>
    </article>
  <?php } ?>
  <?php require '/paginator.phtml'; ?>
<?php } else { ?>
  <article>
    <p>There are no posts.</p>
  </article>
<?php } ?>