<div class="social-login">
  Login using social media
  <img src="/style/facebook_login.png" alt="Login using Facebook" title="Login using Facebook">
  <form action="/login/twitter" method="post">
    <input type="hidden" name="current_url" value="<?php echo $this->request->getUri(); ?>">
    <input type="image" src="/style/twitter_login.png" alt="Login using Twitter" title="Login using Twitter">
  </form>
  <a href="/login/google">
    <img src="/style/googleplus_login.png" alt="Login using Google+" title="Login using Google+">
  </a>
</div>