<!DOCTYPE html>
<html>
  <head>
    <title>Yadeo Blog!</title>
    <link href='http://fonts.googleapis.com/css?family=Droid+Sans' rel='stylesheet' type='text/css'>
    <link rel="stylesheet" type="text/css" href="/style/style.css">
  </head>
  <body>
    <header>
      <h1><a href="/">Yadeo Blog!</a></h1>
      <p>You have successfully installed a new Yadeo blog!</p>
      <form action="/search" method="get">
        <input type="text" name="q" placeholder="Keyword(s)">
        <input type="submit" name="submit" value="Search">
      </form>
    </header>
    <div id="body">
      {{content}}
      <x?php include('/articles.phtml'); ?>
    </div>
    <footer>
    </footer>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.7.2/jquery.min.js"></script>
    <script src="/js/prettify.js"></script>
    <script src="/js/site.js"></script>
  </body>
</html>